In [1]:
import os, re
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io

#from google.colab import files
#uploaded = files.upload()

#from google.colab import drive
#drive.mount('/content/gdrive')

In [ ]:
prob="2clsr"
form="cutStd"
mip_="lp"
inst_="csifa"

In [65]:
con="const60"

df = []
#path=f"/content/gdrive/My Drive/problems/2clsr/results/{form}/{inst_}/all_{prob}_{form}_{mip_}_{inst_}.txt"
path=f"/home/jossian/repository/2clsr_problem/result/{form}/{inst_}/set01_02_{con}_{prob}_{form}_{mip_}_{inst_}.txt"

try:
    df.append(pd.read_csv(path,header=None,sep=';'))
except pd.errors.EmptyDataError:
    print('arquivo vazio!',a)

table = pd.DataFrame()

#table = pd.concat([table, df], ignore_index=True)
table = table.append(df, ignore_index= True)
        
table.columns = ['instance','form','sty','lb','time']

table = table.append({
    'instance':f"{inst_}",
    'form':f"{form}",
    'sty':f"{mip_}",
    'lb':table['lb'].mean(),
    'time':table['time'].mean()
    }, ignore_index= True)

std_lp = table.round(2)
#std_lp

##################################3

set = "set01"

tab = pd.DataFrame()
for i in range(1,13):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set01_std_con60 = tab.round(2)
#set01_std_con60

##################

set = "set02"

tab = pd.DataFrame()
for i in range(13,25):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set02_std_con60 = tab.round(2)
#set02_std_con60

con60_std = pd.DataFrame()
con60_std = con60_std.append(set01_std_con60.iloc[12], ignore_index= True)
con60_std = con60_std.append(set02_std_con60.iloc[12], ignore_index= True)
con60_std

/tmp/ipykernel_138450/3323955497.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(df, ignore_index= True)
/tmp/ipykernel_138450/3323955497.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append({
/tmp/ipykernel_138450/3323955497.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/3323955497.py:59: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/3323955497.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_std = con60_std.append(set01_std_con60.iloc[12], ignore_index= True)
/tmp/ipykernel_138450/3323955497.py:72: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_std = con60_std.append(set02_std_con60.iloc[12], ignore_index= True)

  instance      form sty      lb  time
0    set01  cutStd60  lp  7694.4  0.02
1    set02  cutStd60  lp  8328.1  0.02

In [66]:
con="const61"

df = []
#path=f"/content/gdrive/My Drive/problems/2clsr/results/{form}/{inst_}/all_{prob}_{form}_{mip_}_{inst_}.txt"
path=f"/home/jossian/repository/2clsr_problem/result/{form}/{inst_}/set01_02_{con}_{prob}_{form}_{mip_}_{inst_}.txt"

try:
    df.append(pd.read_csv(path,header=None,sep=';'))
except pd.errors.EmptyDataError:
    print('arquivo vazio!',a)

table = pd.DataFrame()

#table = pd.concat([table, df], ignore_index=True)
table = table.append(df, ignore_index= True)
        
table.columns = ['instance','form','sty','lb','time']

table = table.append({
    'instance':f"{inst_}",
    'form':f"{form}",
    'sty':f"{mip_}",
    'lb':table['lb'].mean(),
    'time':table['time'].mean()
    }, ignore_index= True)

std_lp = table.round(2)
#std_lp

##########################

set = "set01"

tab = pd.DataFrame()
for i in range(1,13):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}61",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set01_std_con61 = tab.round(2)
#set01_std_con61

###########################

set = "set02"

tab = pd.DataFrame()
for i in range(13,25):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}61",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set02_std_con61 = tab.round(2)
#set02_std_con61

con61_std = pd.DataFrame()
con61_std = con61_std.append(set01_std_con61.iloc[12], ignore_index= True)
con61_std = con61_std.append(set02_std_con61.iloc[12], ignore_index= True)
con61_std

/tmp/ipykernel_138450/343858924.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(df, ignore_index= True)
/tmp/ipykernel_138450/343858924.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append({
/tmp/ipykernel_138450/343858924.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/343858924.py:59: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/343858924.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con61_std = con61_std.append(set01_std_con61.iloc[12], ignore_index= True)
/tmp/ipykernel_138450/343858924.py:72: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con61_std = con61_std.append(set02_std_con61.iloc[12], ignore_index= True)

  instance      form sty       lb  time
0    set01  cutStd61  lp  4427.31  0.02
1    set02  cutStd61  lp  5027.93  0.02

In [67]:
prob="2clsr"
form="cutStd"
mip_="lp"
inst_="csifa"
con="const62"

df = []
#path=f"/content/gdrive/My Drive/problems/2clsr/results/{form}/{inst_}/all_{prob}_{form}_{mip_}_{inst_}.txt"
path=f"/home/jossian/repository/2clsr_problem/result/{form}/{inst_}/set01_02_{con}_{prob}_{form}_{mip_}_{inst_}.txt"

try:
    df.append(pd.read_csv(path,header=None,sep=';'))
except pd.errors.EmptyDataError:
    print('arquivo vazio!',a)

table = pd.DataFrame()

#table = pd.concat([table, df], ignore_index=True)
table = table.append(df, ignore_index= True)
        
table.columns = ['instance','form','sty','lb','time']

table = table.append({
    'instance':f"{inst_}",
    'form':f"{form}",
    'sty':f"{mip_}",
    'lb':table['lb'].mean(),
    'time':table['time'].mean()
    }, ignore_index= True)

std_lp = table.round(2)
#std_lp

set = "set01"

tab = pd.DataFrame()
for i in range(1,13):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}62",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set01_std_con62 = tab.round(2)
#set01_std_con62

set = "set02"

tab = pd.DataFrame()
for i in range(13,25):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}62",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set02_std_con62 = tab.round(2)
#set02_std_con62

con62_std = pd.DataFrame()
con62_std = con62_std.append(set01_std_con62.iloc[12], ignore_index= True)
con62_std = con62_std.append(set02_std_con62.iloc[12], ignore_index= True)
con62_std

/tmp/ipykernel_138450/495110641.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(df, ignore_index= True)
/tmp/ipykernel_138450/495110641.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append({
/tmp/ipykernel_138450/495110641.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/495110641.py:59: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/495110641.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con62_std = con62_std.append(set01_std_con62.iloc[12], ignore_index= True)
/tmp/ipykernel_138450/495110641.py:72: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con62_std = con62_std.append(set02_std_con62.iloc[12], ignore_index= True)

  instance      form sty       lb  time
0    set01  cutStd62  lp  7997.53  0.02
1    set02  cutStd62  lp  8739.72  0.02

In [71]:
prob="2clsr"
form="cutStd"
mip_="lp"
inst_="csifa"
con="const63"

df = []
#path=f"/content/gdrive/My Drive/problems/2clsr/results/{form}/{inst_}/all_{prob}_{form}_{mip_}_{inst_}.txt"
path=f"/home/jossian/repository/2clsr_problem/result/{form}/{inst_}/set01_02_{con}_{prob}_{form}_{mip_}_{inst_}.txt"

try:
    df.append(pd.read_csv(path,header=None,sep=';'))
except pd.errors.EmptyDataError:
    print('arquivo vazio!',a)

table = pd.DataFrame()

#table = pd.concat([table, df], ignore_index=True)
table = table.append(df, ignore_index= True)
        
table.columns = ['instance','form','sty','lb','time']

table = table.append({
    'instance':f"{inst_}",
    'form':f"{form}",
    'sty':f"{mip_}",
    'lb':table['lb'].mean(),
    'time':table['time'].mean()
    }, ignore_index= True)

std_lp = table.round(2)
#std_lp

set = "set01"

tab = pd.DataFrame()
for i in range(1,13):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}63",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set01_std_con63 = tab.round(2)
#set01_std_con63

set = "set02"

tab = pd.DataFrame()
for i in range(13,25):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}63",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set02_std_con63 = tab.round(2)
#set02_std_con63

con63_std = pd.DataFrame()
con63_std = con63_std.append(set01_std_con63.iloc[12], ignore_index= True)
con63_std = con63_std.append(set02_std_con63.iloc[12], ignore_index= True)
con63_std

/tmp/ipykernel_138450/592390497.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(df, ignore_index= True)
/tmp/ipykernel_138450/592390497.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append({
/tmp/ipykernel_138450/592390497.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/592390497.py:59: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/592390497.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con63_std = con63_std.append(set01_std_con63.iloc[12], ignore_index= True)
/tmp/ipykernel_138450/592390497.py:72: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con63_std = con63_std.append(set02_std_con63.iloc[12], ignore_index= True)

  instance      form  sty       lb  time
0    set01  cutStd63  NaN  4729.61   NaN
1    set02  cutStd63  NaN  5333.80   NaN

In [69]:
lp = pd.merge(con60_std, con61_std, on='instance')
lp = pd.merge(lp, con62_std, on='instance')
lp = pd.merge(lp, con63_std, on='instance')
lp

/tmp/ipykernel_138450/2584575037.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'lb_x', 'sty_x', 'time_x', 'form_x'} in the result is deprecated and will raise a MergeError in a future version.
  lp = pd.merge(lp, con63_std, on='instance')

,instance,form_x,sty_x,lb_x,time_x,form_y,sty_y,lb_y,time_y,form_x,sty_x,lb_x,time_x,form_y,sty_y,lb_y,time_y
0,set01,cutStd60,lp,7694.4,0.02,cutStd61,lp,4427.31,0.02,cutStd62,lp,7997.53,0.02,cutStd63,lp,4729.61,0.02
1,set02,cutStd60,lp,8328.1,0.02,cutStd61,lp,5027.93,0.02,cutStd62,lp,8739.72,0.02,cutStd63,lp,5333.80,0.02

In [75]:
print(lp[["instance","lb_x","lb_y"]].to_latex(index=False))

\begin{tabular}{lrrrr}
\toprule
instance &   lb\_x &    lb\_x &    lb\_y &    lb\_y \\
\midrule
   set01 & 7694.4 & 7997.53 & 4427.31 & 4729.61 \\
   set02 & 8328.1 & 8739.72 & 5027.93 & 5333.80 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_138450/1052509268.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(lp[["instance","lb_x","lb_y"]].to_latex(index=False))

In [77]:
prob="2clsr"
form="cutStd"
mip_="lp"
inst_="csifa"
con="const60_61"

df = []
#path=f"/content/gdrive/My Drive/problems/2clsr/results/{form}/{inst_}/all_{prob}_{form}_{mip_}_{inst_}.txt"
path=f"/home/jossian/repository/2clsr_problem/result/{form}/{inst_}/set01_02_{con}_{prob}_{form}_{mip_}_{inst_}.txt"

try:
    df.append(pd.read_csv(path,header=None,sep=';'))
except pd.errors.EmptyDataError:
    print('arquivo vazio!',a)

table = pd.DataFrame()

#table = pd.concat([table, df], ignore_index=True)
table = table.append(df, ignore_index= True)
        
table.columns = ['instance','form','sty','lb','time']

table = table.append({
    'instance':f"{inst_}",
    'form':f"{form}",
    'sty':f"{mip_}",
    'lb':table['lb'].mean(),
    'time':table['time'].mean()
    }, ignore_index= True)

std_lp = table.round(2)
#std_lp

set = "set01"

tab = pd.DataFrame()
for i in range(1,13):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60_61",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set01_std_con60_61 = tab.round(2)
#set01_std_con60_61

set = "set02"

tab = pd.DataFrame()
for i in range(13,25):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60_61",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set02_std_con60_61 = tab.round(2)
#set02_std_con60_61

con60_61_std = pd.DataFrame()
con60_61_std = con60_61_std.append(set01_std_con60_61.iloc[12], ignore_index= True)
con60_61_std = con60_61_std.append(set02_std_con60_61.iloc[12], ignore_index= True)
con60_61_std

/tmp/ipykernel_138450/3032442321.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(df, ignore_index= True)
/tmp/ipykernel_138450/3032442321.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append({
/tmp/ipykernel_138450/3032442321.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/3032442321.py:59: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/3032442321.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_61_std = con60_61_std.append(set01_std_con60_61.iloc[12], ignore_index= True)
/tmp/ipykernel_138450/3032442321.py:72: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_61_std = con60_61_std.append(set02_std_con60_61.iloc[12], ignore_index= True)

  instance         form sty       lb  time
0    set01  cutStd60_61  lp  8297.57  0.07
1    set02  cutStd60_61  lp  8902.81  0.07

In [78]:
prob="2clsr"
form="cutStd"
mip_="lp"
inst_="csifa"
con="const60_61_62"

df = []
#path=f"/content/gdrive/My Drive/problems/2clsr/results/{form}/{inst_}/all_{prob}_{form}_{mip_}_{inst_}.txt"
path=f"/home/jossian/repository/2clsr_problem/result/{form}/{inst_}/set01_02_{con}_{prob}_{form}_{mip_}_{inst_}.txt"

try:
    df.append(pd.read_csv(path,header=None,sep=';'))
except pd.errors.EmptyDataError:
    print('arquivo vazio!',a)

table = pd.DataFrame()

#table = pd.concat([table, df], ignore_index=True)
table = table.append(df, ignore_index= True)
        
table.columns = ['instance','form','sty','lb','time']

table = table.append({
    'instance':f"{inst_}",
    'form':f"{form}",
    'sty':f"{mip_}",
    'lb':table['lb'].mean(),
    'time':table['time'].mean()
    }, ignore_index= True)

std_lp = table.round(2)
#std_lp

set = "set01"

tab = pd.DataFrame()
for i in range(1,13):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60_61_62",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set01_std_con60_61_62 = tab.round(2)
#set01_std_con60_61_62

set = "set02"

tab = pd.DataFrame()
for i in range(13,25):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60_61_62",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set02_std_con60_61_62 = tab.round(2)
#set02_std_con60_61_62

con60_61_62_std = pd.DataFrame()
con60_61_62_std = con60_61_62_std.append(set01_std_con60_61_62.iloc[12], ignore_index= True)
con60_61_62_std = con60_61_62_std.append(set02_std_con60_61_62.iloc[12], ignore_index= True)
con60_61_62_std

/tmp/ipykernel_138450/3293637982.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(df, ignore_index= True)
/tmp/ipykernel_138450/3293637982.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append({
/tmp/ipykernel_138450/3293637982.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/3293637982.py:59: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/3293637982.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_61_62_std = con60_61_62_std.append(set01_std_con60_61_62.iloc[12], ignore_index= True)
/tmp/ipykernel_138450/3293637982.py:72: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_61_62_std = con60_61_62_std.append(set02_std_con60_61_62.iloc[12], ignore_index= True)

  instance            form sty       lb  time
0    set01  cutStd60_61_62  lp  8510.37  0.13
1    set02  cutStd60_61_62  lp  9218.38  0.13

In [79]:
prob="2clsr"
form="cutStd"
mip_="lp"
inst_="csifa"
con="const60_61_62_63"

df = []
#path=f"/content/gdrive/My Drive/problems/2clsr/results/{form}/{inst_}/all_{prob}_{form}_{mip_}_{inst_}.txt"
path=f"/home/jossian/repository/2clsr_problem/result/{form}/{inst_}/set01_02_{con}_{prob}_{form}_{mip_}_{inst_}.txt"

try:
    df.append(pd.read_csv(path,header=None,sep=';'))
except pd.errors.EmptyDataError:
    print('arquivo vazio!',a)

table = pd.DataFrame()

#table = pd.concat([table, df], ignore_index=True)
table = table.append(df, ignore_index= True)
        
table.columns = ['instance','form','sty','lb','time']

table = table.append({
    'instance':f"{inst_}",
    'form':f"{form}",
    'sty':f"{mip_}",
    'lb':table['lb'].mean(),
    'time':table['time'].mean()
    }, ignore_index= True)

std_lp = table.round(2)
#std_lp

set = "set01"

tab = pd.DataFrame()
for i in range(1,13):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60_61_62_63",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set01_std_con60_61_62_63 = tab.round(2)
#set01_std_con60_61_62_63

set = "set02"

tab = pd.DataFrame()
for i in range(13,25):
    t = std_lp.loc[std_lp['instance'] == f'instances/csifa/c52_{i}.txt']
    tab = pd.concat([tab,t])
    
tab = tab.append({
    'instance':f'{set}',
    'form':f"{form}60_61_62_63",
    'sty':f"{mip_}",
    'lb':tab['lb'].mean(),
    'time':tab['time'].mean()
    }, ignore_index= True)

set02_std_con60_61_62_63 = tab.round(2)
#set02_std_con60_61_62_63

con60_61_62_63_std = pd.DataFrame()
con60_61_62_63_std = con60_61_62_63_std.append(set01_std_con60_61_62_63.iloc[12], ignore_index= True)
con60_61_62_63_std = con60_61_62_63_std.append(set02_std_con60_61_62_63.iloc[12], ignore_index= True)
con60_61_62_63_std

/tmp/ipykernel_138450/1178659656.py:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(df, ignore_index= True)
/tmp/ipykernel_138450/1178659656.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append({
/tmp/ipykernel_138450/1178659656.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/1178659656.py:59: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tab = tab.append({
/tmp/ipykernel_138450/1178659656.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_61_62_63_std = con60_61_62_63_std.append(set01_std_con60_61_62_63.iloc[12], ignore_index= True)
/tmp/ipykernel_138450/1178659656.py:72: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  con60_61_62_63_std = con60_61_62_63_std.append(set02_std_con60_61_62_63.iloc[12], ignore_index= True)

  instance               form sty       lb  time
0    set01  cutStd60_61_62_63  lp  8513.06  0.11
1    set02  cutStd60_61_62_63  lp  9218.86  0.11

In [80]:
cut_lp = pd.merge(con60_61_std, con60_61_62_std, on='instance')
cut_lp = pd.merge(cut_lp, con60_61_62_63_std, on='instance')
#cut_lp = pd.merge(lp, con63_std, on='instance')
cut_lp

,instance,form_x,sty_x,lb_x,time_x,form_y,sty_y,lb_y,time_y,form,sty,lb,time
0,set01,cutStd60_61,lp,8297.57,0.07,cutStd60_61_62,lp,8510.37,0.13,cutStd60_61_62_63,lp,8513.06,0.11
1,set02,cutStd60_61,lp,8902.81,0.07,cutStd60_61_62,lp,9218.38,0.13,cutStd60_61_62_63,lp,9218.86,0.11

In [82]:
print(cut_lp[["instance","lb_x","lb_y","lb"]].to_latex(index=False))

\begin{tabular}{lrrr}
\toprule
instance &    lb\_x &    lb\_y &      lb \\
\midrule
   set01 & 8297.57 & 8510.37 & 8513.06 \\
   set02 & 8902.81 & 9218.38 & 9218.86 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_138450/2963525121.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(cut_lp[["instance","lb_x","lb_y","lb"]].to_latex(index=False))