In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
inst_="karate"
method_="mip"

In [31]:
form_="fmin"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fmin = table
mip_karate_fmin

#print(mip_karate_fmin[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.02    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.14    9.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.07    7.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.17    9.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.09    5.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.07    7.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.28    6.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.14   16.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.17   13.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.10    7.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.13    6.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.25   11.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.02    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  1.68  102.0  34.0  21.0  0.28

In [32]:
form_="fmax"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fmax = table
mip_karate_fmax

#print(mip_karate_fmax[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.02    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.16   11.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    1.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    1.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    1.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.08    3.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.20   10.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.08    7.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.09    7.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.19    8.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.15   14.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.20   10.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.12    7.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.12    5.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.12    6.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.02    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  1.58   99.0  34.0  21.0   0.2

In [33]:
form_="fmaxmisetn0"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fmaxmisetn0 = table
mip_karate_fmaxmisetn0

#print(mip_internet_fmaxmisetn0[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.02    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.24    2.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.01    1.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.01    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.01    1.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.01    1.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.15    1.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.27    5.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.01    1.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.10    3.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.10    5.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.34    5.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.60    3.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.37    9.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.20    1.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.20    1.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.01    1.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.24    3.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.02    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  2.94   49.0  34.0  21.0   0.6

In [34]:
form_="fminmisetn0"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminmisetn0 = table
mip_karate_fminmisetn0

#print(mip_karate_fminmisetn0[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.02    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.15    3.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.02    1.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.18    5.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.07    2.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.10    2.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.21    3.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.27    5.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.14    9.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.17    7.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.12    3.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.19    3.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  1.68   49.0  34.0  21.0  0.27

In [35]:
form_="fminmisetn1"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminmisetn1 = table
mip_karate_fminmisetn1

#print(mip_karate_fminmisetn1[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.02    1.0   1.0   NaN   NaN
1        1    7.0    7.0  0.0  0.00    1.0   1.0   NaN   NaN
2        2   17.0   17.0  0.0  0.00    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   17.0   17.0  0.0  0.03    1.0   1.0   NaN   NaN
9        9   15.0   15.0  0.0  0.07    3.0   1.0   NaN   NaN
10      10    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   16.0   16.0  0.0  0.00    1.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   16.0   16.0  0.0  0.00    1.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
24      24   16.0   16.0  0.0  0.14    7.0   1.0   NaN   NaN
25      25   15.0   15.0  0.0  0.10    3.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   16.0   16.0  0.0  0.03    1.0   1.0   NaN   NaN
28      28   16.0   16.0  0.0  0.07    1.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   12.0   12.0  0.0  0.02    1.0   1.0   NaN   NaN
31      31   17.0   17.0  0.0  0.01    1.0   1.0   NaN   NaN
32      32   17.0   17.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  266.0  266.0  0.0  0.51   25.0  34.0  21.0  0.14

In [36]:
form_="fminmiset"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminmiset = table
mip_karate_fminmiset

#print(mip_karate_fminmiset[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   15.0   15.0  0.0  0.00    1.0   1.0   NaN   NaN
1        1    6.0    6.0  0.0  0.00    0.0   1.0   NaN   NaN
2        2   11.0   11.0  0.0  0.00    1.0   1.0   NaN   NaN
3        3    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
5        5    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8    6.0    6.0  0.0  0.00    1.0   1.0   NaN   NaN
9        9    6.0    6.0  0.0  0.00    1.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19    6.0    6.0  0.0  0.00    1.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   13.0   13.0  0.0  0.01    1.0   1.0   NaN   NaN
24      24    4.0    4.0  0.0  0.00    1.0   1.0   NaN   NaN
25      25   10.0   10.0  0.0  0.01    1.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27    4.0    4.0  0.0  0.00    0.0   1.0   NaN   NaN
28      28    6.0    6.0  0.0  0.00    1.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
31      31   14.0   14.0  0.0  0.00    1.0   1.0   NaN   NaN
32      32   12.0   12.0  0.0  0.00    1.0   1.0   NaN   NaN
33      33   14.0   14.0  0.0  0.00    1.0   1.0   NaN   NaN
34     mip  156.0  156.0  0.0  0.02   12.0  34.0  15.0  0.01

In [37]:
result = pd.DataFrame()

result = pd.merge(
    mip_karate_fmin, mip_karate_fmax,
    on=['vertice'], 
    suffixes=("", "_fmax"),
    )

result = pd.merge(
    result, mip_karate_fminmisetn0,
    on=['vertice'], 
    suffixes=("", "_fminmisetn0"),
    )

result = pd.merge(
    result, mip_karate_fmaxmisetn0,
    on=['vertice'], 
    suffixes=("", "_fmaxmisetn0"),
    )

result = pd.merge(
    result, mip_karate_fminmiset,
    on=['vertice'], 
    suffixes=("", "_fminmiset"),
    )

result = pd.merge(
    result, mip_karate_fminmisetn1,
    on=['vertice'], 
    suffixes=("", "_fminmisetn1"),
    )

In [38]:
result[[
    'vertice',
    'bs','gap','time','opt','tk','tmax',
    'bs_fmax','gap_fmax','time_fmax','opt_fmax','tk_fmax','tmax_fmax',
    'bs_fminmisetn0','gap_fminmisetn0','time_fminmisetn0','opt_fminmisetn0','tk_fminmisetn0','tmax_fminmisetn0',
    'bs_fmaxmisetn0','gap_fmaxmisetn0','time_fmaxmisetn0','opt_fmaxmisetn0','tk_fmaxmisetn0','tmax_fmaxmisetn0',
    'bs_fminmiset','gap_fminmiset','time_fminmiset','opt_fminmiset','tk_fminmiset','tmax_fminmiset',
    'bs_fminmisetn1','gap_fminmisetn1','time_fminmisetn1','opt_fminmisetn1','tk_fminmisetn1','tmax_fminmisetn1'
    ]]

,vertice,bs,gap,time,opt,tk,tmax,bs_fmax,gap_fmax,time_fmax,...,time_fminmiset,opt_fminmiset,tk_fminmiset,tmax_fminmiset,bs_fminmisetn1,gap_fminmisetn1,time_fminmisetn1,opt_fminmisetn1,tk_fminmisetn1,tmax_fminmisetn1
0,0,21.0,0.0,0.02,1.0,NaN,NaN,21.0,0.0,0.02,...,0.00,1.0,NaN,NaN,21.0,0.0,0.02,1.0,NaN,NaN
1,1,21.0,0.0,0.14,1.0,NaN,NaN,21.0,0.0,0.16,...,0.00,1.0,NaN,NaN,7.0,0.0,0.00,1.0,NaN,NaN
2,2,19.0,0.0,0.01,1.0,NaN,NaN,19.0,0.0,0.01,...,0.00,1.0,NaN,NaN,17.0,0.0,0.00,1.0,NaN,NaN
3,3,3.0,0.0,0.00,1.0,NaN,NaN,3.0,0.0,0.00,...,0.00,1.0,NaN,NaN,3.0,0.0,0.00,1.0,NaN,NaN
4,4,2.0,0.0,0.00,1.0,NaN,NaN,2.0,0.0,0.00,...,0.00,1.0,NaN,NaN,2.0,0.0,0.00,1.0,NaN,NaN
5,5,3.0,0.0,0.00,1.0,NaN,NaN,3.0,0.0,0.00,...,0.00,1.0,NaN,NaN,3.0,0.0,0.00,1.0,NaN,NaN
6,6,3.0,0.0,0.00,1.0,NaN,NaN,3.0,0.0,0.00,...,0.00,1.0,NaN,NaN,3.0,0.0,0.00,1.0,NaN,NaN
7,7,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
8,8,19.0,0.0,0.07,1.0,NaN,NaN,19.0,0.0,0.08,...,0.00,1.0,NaN,NaN,17.0,0.0,0.03,1.0,NaN,NaN
9,9,19.0,0.0,0.17,1.0,NaN,NaN,19.0,0.0,0.20,...,0.00,1.0,NaN,NaN,15.0,0.0,0.07,1.0,NaN,NaN
10,10,2.0,0.0,0.00,1.0,NaN,NaN,2.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
11,11,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
12,12,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
13,13,19.0,0.0,0.09,1.0,NaN,NaN,19.0,0.0,0.08,...,0.00,1.0,NaN,NaN,16.0,0.0,0.00,1.0,NaN,NaN
14,14,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
15,15,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
16,16,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
17,17,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
18,18,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
19,19,19.0,0.0,0.07,1.0,NaN,NaN,19.0,0.0,0.09,...,0.00,1.0,NaN,NaN,16.0,0.0,0.00,1.0,NaN,NaN
20,20,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
21,21,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
22,22,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
23,23,19.0,0.0,0.28,1.0,NaN,NaN,19.0,0.0,0.19,...,0.01,1.0,NaN,NaN,3.0,0.0,0.00,1.0,NaN,NaN
24,24,19.0,0.0,0.14,1.0,NaN,NaN,19.0,0.0,0.15,...,0.00,1.0,NaN,NaN,16.0,0.0,0.14,1.0,NaN,NaN
25,25,19.0,0.0,0.17,1.0,NaN,NaN,19.0,0.0,0.20,...,0.01,1.0,NaN,NaN,15.0,0.0,0.10,1.0,NaN,NaN
26,26,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
27,27,19.0,0.0,0.10,1.0,NaN,NaN,19.0,0.0,0.12,...,0.00,1.0,NaN,NaN,16.0,0.0,0.03,1.0,NaN,NaN
28,28,19.0,0.0,0.13,1.0,NaN,NaN,19.0,0.0,0.12,...,0.00,1.0,NaN,NaN,16.0,0.0,0.07,1.0,NaN,NaN
29,29,2.0,0.0,0.00,1.0,NaN,NaN,2.0,0.0,0.00,...,0.00,1.0,NaN,NaN,2.0,0.0,0.00,1.0,NaN,NaN
30,30,19.0,0.0,0.25,1.0,NaN,NaN,19.0,0.0,0.12,...,0.00,1.0,NaN,NaN,12.0,0.0,0.02,1.0,NaN,NaN
31,31,19.0,0.0,0.02,1.0,NaN,NaN,19.0,0.0,0.02,...,0.00,1.0,NaN,NaN,17.0,0.0,0.01,1.0,NaN,NaN
32,32,19.0,0.0,0.01,1.0,NaN,NaN,19.0,0.0,0.01,...,0.00,1.0,NaN,NaN,17.0,0.0,0.01,1.0,NaN,NaN
33,33,19.0,0.0,0.01,1.0,NaN,NaN,19.0,0.0,0.01,...,0.00,1.0,NaN,NaN,19.0,0.0,0.01,1.0,NaN,NaN
34,mip,335.0,0.0,1.68,34.0,21.0,0.28,335.0,0.0,1.58,...,0.02,34.0,15.0,0.01,266.0,0.0,0.51,34.0,21.0,0.14

In [39]:
print(
result[[
    'vertice',
    'bs','gap','time','opt','tk','tmax',
    'bs_fmax','gap_fmax','time_fmax','opt_fmax','tk_fmax','tmax_fmax',
    'bs_fminmisetn0','gap_fminmisetn0','time_fminmisetn0','opt_fminmisetn0','tk_fminmisetn0','tmax_fminmisetn0',
    'bs_fmaxmisetn0','gap_fmaxmisetn0','time_fmaxmisetn0','opt_fmaxmisetn0','tk_fmaxmisetn0','tmax_fmaxmisetn0',
    'bs_fminmiset','gap_fminmiset','time_fminmiset','opt_fminmiset','tk_fminmiset','tmax_fminmiset',
    'bs_fminmisetn1','gap_fminmisetn1','time_fminmisetn1','opt_fminmisetn1','tk_fminmisetn1','tmax_fminmisetn1'
    ]].to_latex(index=False,float_format="%.1f")
    )

\begin{tabular}{lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr}
\toprule
vertice & bs & gap & time & opt & tk & tmax & bs_fmax & gap_fmax & time_fmax & opt_fmax & tk_fmax & tmax_fmax & bs_fminmisetn0 & gap_fminmisetn0 & time_fminmisetn0 & opt_fminmisetn0 & tk_fminmisetn0 & tmax_fminmisetn0 & bs_fmaxmisetn0 & gap_fmaxmisetn0 & time_fmaxmisetn0 & opt_fmaxmisetn0 & tk_fmaxmisetn0 & tmax_fmaxmisetn0 & bs_fminmiset & gap_fminmiset & time_fminmiset & opt_fminmiset & tk_fminmiset & tmax_fminmiset & bs_fminmisetn1 & gap_fminmisetn1 & time_fminmisetn1 & opt_fminmisetn1 & tk_fminmisetn1 & tmax_fminmisetn1 \\
\midrule
0 & 21.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 21.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 21.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 21.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 15.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 21.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
1 & 21.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 21.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 21.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 21.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 6.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 7.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
2 & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 11.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 17.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
3 & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
4 & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
5 & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
6 & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
7 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
8 & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 6.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 17.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
9 & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.3 & 1.0 & NaN & NaN & 6.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 15.0 & 0.0 & 0.1 & 1.0 & NaN & NaN \\
10 & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
11 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
12 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
13 & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 16.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
14 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
15 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
16 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
17 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
18 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
19 & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 6.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 16.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
20 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
21 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
22 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
23 & 19.0 & 0.0 & 0.3 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.3 & 1.0 & NaN & NaN & 13.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 3.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
24 & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.3 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.6 & 1.0 & NaN & NaN & 4.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 16.0 & 0.0 & 0.1 & 1.0 & NaN & NaN \\
25 & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.4 & 1.0 & NaN & NaN & 10.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 15.0 & 0.0 & 0.1 & 1.0 & NaN & NaN \\
26 & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 1.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
27 & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 4.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 16.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
28 & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 6.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 16.0 & 0.0 & 0.1 & 1.0 & NaN & NaN \\
29 & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
30 & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.1 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.2 & 1.0 & NaN & NaN & 2.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 12.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
31 & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 14.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 17.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
32 & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 12.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 17.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
33 & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 14.0 & 0.0 & 0.0 & 1.0 & NaN & NaN & 19.0 & 0.0 & 0.0 & 1.0 & NaN & NaN \\
mip & 335.0 & 0.0 & 1.7 & 34.0 & 21.0 & 0.3 & 335.0 & 0.0 & 1.6 & 34.0 & 21.0 & 0.2 & 335.0 & 0.0 & 1.7 & 34.0 & 21.0 & 0.3 & 335.0 & 0.0 & 2.9 & 34.0 & 21.0 & 0.6 & 156.0 & 0.0 & 0.0 & 34.0 & 15.0 & 0.0 & 266.0 & 0.0 & 0.5 & 34.0 & 21.0 & 0.1 \\
\bottomrule
\end{tabular}

In [40]:
#prprint(
#result[['vertice','bb','bb_max','bb_minmiset','bb_maxmiset']].to_latex(index=False,float_format="%.1f")
#)

with open('../result/karate_mip.tex', 'w') as tf:
     tf.write(
          result[[
          'vertice',
          'bs','gap','time',
          'bs_fmax','gap_fmax','time_fmax',
          'bs_fminmisetn0','gap_fminmisetn0','time_fminmisetn0',
          'bs_fmaxmisetn0','gap_fmaxmisetn0','time_fmaxmisetn0',
          'bs_fminmiset','gap_fminmiset','time_fminmiset',
          'bs_fminmisetn1','gap_fminmisetn1','time_fminmisetn1'
          ]].to_latex(index=False,float_format="%.1f")
    )