In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
inst_="karate"
method_="lp"

In [32]:
form_="fmin"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','time','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'time':table['time'].sum(),
    'opt':table['opt'].sum(),
    'tk':table['bb'].max()
    },index=[f"{inst_}"]
)

table = pd.concat([table, resume], ignore_index=True)
lp_karate_fmin = table
lp_karate_fmin

#print(lp_karate_fmin[['vertice','bb','time','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb  time   opt    tk
0        0   16.2   0.0   1.0   NaN
1        1   11.0   0.0   1.0   NaN
2        2   14.2   0.0   1.0   NaN
3        3    3.0   0.0   1.0   NaN
4        4    2.0   0.0   1.0   NaN
5        5    3.0   0.0   1.0   NaN
6        6    3.0   0.0   1.0   NaN
7        7    1.0   0.0   1.0   NaN
8        8   12.5   0.0   1.0   NaN
9        9    9.2   0.0   1.0   NaN
10      10    2.0   0.0   1.0   NaN
11      11    1.0   0.0   1.0   NaN
12      12    1.0   0.0   1.0   NaN
13      13   12.5   0.0   1.0   NaN
14      14    1.0   0.0   1.0   NaN
15      15    1.0   0.0   1.0   NaN
16      16    1.0   0.0   1.0   NaN
17      17    1.0   0.0   1.0   NaN
18      18    1.0   0.0   1.0   NaN
19      19   12.0   0.0   1.0   NaN
20      20    1.0   0.0   1.0   NaN
21      21    1.0   0.0   1.0   NaN
22      22    1.0   0.0   1.0   NaN
23      23    7.6   0.0   1.0   NaN
24      24    7.5   0.0   1.0   NaN
25      25    6.9   0.0   1.0   NaN
26      26    1.0   0.0   1.0   NaN
27      27   10.3   0.0   1.0   NaN
28      28    9.9   0.0   1.0   NaN
29      29    2.0   0.0   1.0   NaN
30      30    8.7   0.0   1.0   NaN
31      31   13.0   0.0   1.0   NaN
32      32   12.0   0.0   1.0   NaN
33      33   12.0   0.0   1.0   NaN
34      lp  202.5   0.0  34.0  16.2

In [33]:
form_="fminmiset"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','time','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'time':table['time'].sum(),
    'opt':table['opt'].sum(),
    'tk':table['bb'].max()
    },index=[f"{inst_}"]
)

table = pd.concat([table, resume], ignore_index=True)
lp_karate_fminmiset = table
lp_karate_fminmiset

#print(lp_karate_fminmiset[['vertice','bb','time','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb  time   opt    tk
0        0   11.4   0.0   1.0   NaN
1        1    6.5   0.0   1.0   NaN
2        2    5.5   0.0   1.0   NaN
3        3    2.0   0.0   1.0   NaN
4        4    2.0   0.0   1.0   NaN
5        5    2.0   0.0   1.0   NaN
6        6    2.0   0.0   1.0   NaN
7        7    1.0   0.0   1.0   NaN
8        8    5.2   0.0   1.0   NaN
9        9    3.4   0.0   1.0   NaN
10      10    1.0   0.0   1.0   NaN
11      11    1.0   0.0   1.0   NaN
12      12    1.0   0.0   1.0   NaN
13      13    5.1   0.0   1.0   NaN
14      14    1.0   0.0   1.0   NaN
15      15    1.0   0.0   1.0   NaN
16      16    1.0   0.0   1.0   NaN
17      17    1.0   0.0   1.0   NaN
18      18    1.0   0.0   1.0   NaN
19      19    8.8   0.0   1.0   NaN
20      20    1.0   0.0   1.0   NaN
21      21    1.0   0.0   1.0   NaN
22      22    1.0   0.0   1.0   NaN
23      23    3.0   0.0   1.0   NaN
24      24    2.0   0.0   1.0   NaN
25      25    2.4   0.0   1.0   NaN
26      26    1.0   0.0   1.0   NaN
27      27    3.5   0.0   1.0   NaN
28      28    4.7   0.0   1.0   NaN
29      29    2.0   0.0   1.0   NaN
30      30    2.0   0.0   1.0   NaN
31      31   10.8   0.0   1.0   NaN
32      32   12.3   0.0   1.0   NaN
33      33   14.0   0.0   1.0   NaN
34      lp  123.6   0.0  34.0  14.0

In [34]:
form_="fminmisetn0"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','time','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'time':table['time'].sum(),
    'opt':table['opt'].sum(),
    'tk':table['bb'].max()
    },index=[f"{inst_}"]
)

table = pd.concat([table, resume], ignore_index=True)
lp_karate_fminmisetn0 = table
lp_karate_fminmisetn0

#print(lp_karate_fminmisetn0[['vertice','bb','time','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb  time   opt    tk
0        0   17.8   0.0   1.0   NaN
1        1   12.0   0.0   1.0   NaN
2        2   16.1   0.0   1.0   NaN
3        3    3.0   0.0   1.0   NaN
4        4    2.0   0.0   1.0   NaN
5        5    3.0   0.0   1.0   NaN
6        6    3.0   0.0   1.0   NaN
7        7    1.0   0.0   1.0   NaN
8        8   14.1   0.0   1.0   NaN
9        9    9.4   0.0   1.0   NaN
10      10    2.0   0.0   1.0   NaN
11      11    1.0   0.0   1.0   NaN
12      12    1.0   0.0   1.0   NaN
13      13   13.6   0.0   1.0   NaN
14      14    1.0   0.0   1.0   NaN
15      15    1.0   0.0   1.0   NaN
16      16    1.0   0.0   1.0   NaN
17      17    1.0   0.0   1.0   NaN
18      18    1.0   0.0   1.0   NaN
19      19   13.0   0.0   1.0   NaN
20      20    1.0   0.0   1.0   NaN
21      21    1.0   0.0   1.0   NaN
22      22    1.0   0.0   1.0   NaN
23      23    8.3   0.0   1.0   NaN
24      24    7.5   0.0   1.0   NaN
25      25    6.9   0.0   1.0   NaN
26      26    1.0   0.0   1.0   NaN
27      27   10.6   0.0   1.0   NaN
28      28   10.5   0.0   1.0   NaN
29      29    2.0   0.0   1.0   NaN
30      30    9.3   0.0   1.0   NaN
31      31   15.0   0.0   1.0   NaN
32      32   14.0   0.0   1.0   NaN
33      33   16.6   0.0   1.0   NaN
34      lp  221.7   0.0  34.0  17.8

In [35]:
form_="fminmisetn1"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','time','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'time':table['time'].sum(),
    'opt':table['opt'].sum(),
    'tk':table['bb'].max()
    },index=[f"{inst_}"]
)

table = pd.concat([table, resume], ignore_index=True)
lp_karate_fminmisetn1 = table
lp_karate_fminmisetn1

#print(lp_karate_fminmisetn1[['vertice','bb','time','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb  time   opt    tk
0        0   18.3   0.0   1.0   NaN
1        1   11.1   0.0   1.0   NaN
2        2   15.1   0.0   1.0   NaN
3        3    3.0   0.0   1.0   NaN
4        4    2.0   0.0   1.0   NaN
5        5    2.0   0.0   1.0   NaN
6        6    3.0   0.0   1.0   NaN
7        7    1.0   0.0   1.0   NaN
8        8   12.5   0.0   1.0   NaN
9        9    8.5   0.0   1.0   NaN
10      10    2.0   0.0   1.0   NaN
11      11    1.0   0.0   1.0   NaN
12      12    1.0   0.0   1.0   NaN
13      13   13.2   0.0   1.0   NaN
14      14    1.0   0.0   1.0   NaN
15      15    1.0   0.0   1.0   NaN
16      16    1.0   0.0   1.0   NaN
17      17    1.0   0.0   1.0   NaN
18      18    1.0   0.0   1.0   NaN
19      19   11.8   0.0   1.0   NaN
20      20    1.0   0.0   1.0   NaN
21      21    1.0   0.0   1.0   NaN
22      22    1.0   0.0   1.0   NaN
23      23    5.0   0.0   1.0   NaN
24      24    3.0   0.0   1.0   NaN
25      25    5.0   0.0   1.0   NaN
26      26    1.0   0.0   1.0   NaN
27      27    9.0   0.0   1.0   NaN
28      28    8.4   0.0   1.0   NaN
29      29    2.0   0.0   1.0   NaN
30      30    7.0   0.0   1.0   NaN
31      31   13.5   0.0   1.0   NaN
32      32   14.0   0.0   1.0   NaN
33      33   15.4   0.0   1.0   NaN
34      lp  196.8   0.0  34.0  18.3

In [36]:
form_="fmax"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','time','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'time':table['time'].sum(),
    'opt':table['opt'].sum(),
    'tk':table['bb'].max()
    },index=[f"{inst_}"]
)

table = pd.concat([table, resume], ignore_index=True)
lp_karate_fmax = table
lp_karate_fmax

#print(lp_karate_fmax[['vertice','bb','time','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb  time   opt    tk
0        0   16.2   0.0   1.0   NaN
1        1   11.0   0.0   1.0   NaN
2        2   14.2   0.0   1.0   NaN
3        3    3.0   0.0   1.0   NaN
4        4    2.0   0.0   1.0   NaN
5        5    3.0   0.0   1.0   NaN
6        6    3.0   0.0   1.0   NaN
7        7    1.0   0.0   1.0   NaN
8        8   12.5   0.0   1.0   NaN
9        9    9.2   0.0   1.0   NaN
10      10    2.0   0.0   1.0   NaN
11      11    1.0   0.0   1.0   NaN
12      12    1.0   0.0   1.0   NaN
13      13   12.5   0.0   1.0   NaN
14      14    1.0   0.0   1.0   NaN
15      15    1.0   0.0   1.0   NaN
16      16    1.0   0.0   1.0   NaN
17      17    1.0   0.0   1.0   NaN
18      18    1.0   0.0   1.0   NaN
19      19   12.0   0.0   1.0   NaN
20      20    1.0   0.0   1.0   NaN
21      21    1.0   0.0   1.0   NaN
22      22    1.0   0.0   1.0   NaN
23      23    7.6   0.0   1.0   NaN
24      24    7.5   0.0   1.0   NaN
25      25    6.9   0.0   1.0   NaN
26      26    1.0   0.0   1.0   NaN
27      27   10.3   0.0   1.0   NaN
28      28    9.9   0.0   1.0   NaN
29      29    2.0   0.0   1.0   NaN
30      30    8.7   0.0   1.0   NaN
31      31   13.0   0.0   1.0   NaN
32      32   12.0   0.0   1.0   NaN
33      33   12.0   0.0   1.0   NaN
34      lp  202.5   0.0  34.0  16.2

In [37]:
form_="fmaxmisetn0"

file=f"../result/{inst_}/{method_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','time','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'time':table['time'].sum(),
    'opt':table['opt'].sum(),
    'tk':table['bb'].max()
    },index=[f"{inst_}"]
)

table = pd.concat([table, resume], ignore_index=True)
lp_karate_fmaxmisetn0 = table
lp_karate_fmaxmisetn0

#print(lp_karate_maxmiset[['vertice','bb','time','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb  time   opt    tk
0        0   19.1  0.00   1.0   NaN
1        1   13.0  0.00   1.0   NaN
2        2   17.8  0.00   1.0   NaN
3        3    3.0  0.00   1.0   NaN
4        4    2.0  0.00   1.0   NaN
5        5    3.0  0.00   1.0   NaN
6        6    3.0  0.00   1.0   NaN
7        7    1.0  0.00   1.0   NaN
8        8   15.2  0.00   1.0   NaN
9        9   10.4  0.01   1.0   NaN
10      10    2.0  0.00   1.0   NaN
11      11    1.0  0.00   1.0   NaN
12      12    1.0  0.00   1.0   NaN
13      13   15.2  0.00   1.0   NaN
14      14    1.0  0.00   1.0   NaN
15      15    1.0  0.00   1.0   NaN
16      16    1.0  0.00   1.0   NaN
17      17    1.0  0.00   1.0   NaN
18      18    1.0  0.00   1.0   NaN
19      19   14.5  0.00   1.0   NaN
20      20    1.0  0.00   1.0   NaN
21      21    1.0  0.00   1.0   NaN
22      22    1.0  0.00   1.0   NaN
23      23    8.6  0.00   1.0   NaN
24      24    8.6  0.00   1.0   NaN
25      25    8.4  0.00   1.0   NaN
26      26    1.0  0.00   1.0   NaN
27      27   11.8  0.00   1.0   NaN
28      28   11.0  0.00   1.0   NaN
29      29    2.0  0.00   1.0   NaN
30      30    9.7  0.00   1.0   NaN
31      31   16.7  0.00   1.0   NaN
32      32   16.3  0.00   1.0   NaN
33      33   17.2  0.00   1.0   NaN
34      lp  240.5  0.01  34.0  19.1

In [40]:
result = pd.DataFrame()

result = pd.merge(
    lp_karate_fmin, lp_karate_fmax,
    on=['vertice'], 
    suffixes=("", "_a"),
    )

result = pd.merge(
    result, lp_karate_fminmisetn0,
    on=['vertice'], 
    suffixes=("", "_b"),
    )

result = pd.merge(
    result, lp_karate_fmaxmisetn0,
    on=['vertice'], 
    suffixes=("", "_c"),
    )

result = pd.merge(
    result, lp_karate_fminmiset,
    on=['vertice'], 
    suffixes=("", "_d"),
    )

result = pd.merge(
    result, lp_karate_fminmisetn1,
    on=['vertice'], 
    suffixes=("", "_e"),
    )


result

,vertice,bb,time,opt,tk,bb_a,time_a,opt_a,tk_a,bb_b,...,opt_c,tk_c,bb_d,time_d,opt_d,tk_d,bb_e,time_e,opt_e,tk_e
0,0,16.2,0.0,1.0,NaN,16.2,0.0,1.0,NaN,17.8,...,1.0,NaN,11.4,0.0,1.0,NaN,18.3,0.0,1.0,NaN
1,1,11.0,0.0,1.0,NaN,11.0,0.0,1.0,NaN,12.0,...,1.0,NaN,6.5,0.0,1.0,NaN,11.1,0.0,1.0,NaN
2,2,14.2,0.0,1.0,NaN,14.2,0.0,1.0,NaN,16.1,...,1.0,NaN,5.5,0.0,1.0,NaN,15.1,0.0,1.0,NaN
3,3,3.0,0.0,1.0,NaN,3.0,0.0,1.0,NaN,3.0,...,1.0,NaN,2.0,0.0,1.0,NaN,3.0,0.0,1.0,NaN
4,4,2.0,0.0,1.0,NaN,2.0,0.0,1.0,NaN,2.0,...,1.0,NaN,2.0,0.0,1.0,NaN,2.0,0.0,1.0,NaN
5,5,3.0,0.0,1.0,NaN,3.0,0.0,1.0,NaN,3.0,...,1.0,NaN,2.0,0.0,1.0,NaN,2.0,0.0,1.0,NaN
6,6,3.0,0.0,1.0,NaN,3.0,0.0,1.0,NaN,3.0,...,1.0,NaN,2.0,0.0,1.0,NaN,3.0,0.0,1.0,NaN
7,7,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
8,8,12.5,0.0,1.0,NaN,12.5,0.0,1.0,NaN,14.1,...,1.0,NaN,5.2,0.0,1.0,NaN,12.5,0.0,1.0,NaN
9,9,9.2,0.0,1.0,NaN,9.2,0.0,1.0,NaN,9.4,...,1.0,NaN,3.4,0.0,1.0,NaN,8.5,0.0,1.0,NaN
10,10,2.0,0.0,1.0,NaN,2.0,0.0,1.0,NaN,2.0,...,1.0,NaN,1.0,0.0,1.0,NaN,2.0,0.0,1.0,NaN
11,11,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
12,12,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
13,13,12.5,0.0,1.0,NaN,12.5,0.0,1.0,NaN,13.6,...,1.0,NaN,5.1,0.0,1.0,NaN,13.2,0.0,1.0,NaN
14,14,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
15,15,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
16,16,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
17,17,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
18,18,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
19,19,12.0,0.0,1.0,NaN,12.0,0.0,1.0,NaN,13.0,...,1.0,NaN,8.8,0.0,1.0,NaN,11.8,0.0,1.0,NaN
20,20,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
21,21,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
22,22,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
23,23,7.6,0.0,1.0,NaN,7.6,0.0,1.0,NaN,8.3,...,1.0,NaN,3.0,0.0,1.0,NaN,5.0,0.0,1.0,NaN
24,24,7.5,0.0,1.0,NaN,7.5,0.0,1.0,NaN,7.5,...,1.0,NaN,2.0,0.0,1.0,NaN,3.0,0.0,1.0,NaN
25,25,6.9,0.0,1.0,NaN,6.9,0.0,1.0,NaN,6.9,...,1.0,NaN,2.4,0.0,1.0,NaN,5.0,0.0,1.0,NaN
26,26,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN,1.0,...,1.0,NaN,1.0,0.0,1.0,NaN,1.0,0.0,1.0,NaN
27,27,10.3,0.0,1.0,NaN,10.3,0.0,1.0,NaN,10.6,...,1.0,NaN,3.5,0.0,1.0,NaN,9.0,0.0,1.0,NaN
28,28,9.9,0.0,1.0,NaN,9.9,0.0,1.0,NaN,10.5,...,1.0,NaN,4.7,0.0,1.0,NaN,8.4,0.0,1.0,NaN
29,29,2.0,0.0,1.0,NaN,2.0,0.0,1.0,NaN,2.0,...,1.0,NaN,2.0,0.0,1.0,NaN,2.0,0.0,1.0,NaN
30,30,8.7,0.0,1.0,NaN,8.7,0.0,1.0,NaN,9.3,...,1.0,NaN,2.0,0.0,1.0,NaN,7.0,0.0,1.0,NaN
31,31,13.0,0.0,1.0,NaN,13.0,0.0,1.0,NaN,15.0,...,1.0,NaN,10.8,0.0,1.0,NaN,13.5,0.0,1.0,NaN
32,32,12.0,0.0,1.0,NaN,12.0,0.0,1.0,NaN,14.0,...,1.0,NaN,12.3,0.0,1.0,NaN,14.0,0.0,1.0,NaN
33,33,12.0,0.0,1.0,NaN,12.0,0.0,1.0,NaN,16.6,...,1.0,NaN,14.0,0.0,1.0,NaN,15.4,0.0,1.0,NaN
34,lp,202.5,0.0,34.0,16.2,202.5,0.0,34.0,16.2,221.7,...,34.0,19.1,123.6,0.0,34.0,14.0,196.8,0.0,34.0,18.3

In [42]:
result[[
    'vertice',
    'bb',#'tk',
    'bb_a',#'tk_a',
    'bb_b',#'tk_b',
    'bb_c',#'tk_c',
    'bb_d',#'tk_d',
    'bb_e'#,'tk_e'
    ]]

   vertice     bb   bb_a   bb_b   bb_c   bb_d   bb_e
0        0   16.2   16.2   17.8   19.1   11.4   18.3
1        1   11.0   11.0   12.0   13.0    6.5   11.1
2        2   14.2   14.2   16.1   17.8    5.5   15.1
3        3    3.0    3.0    3.0    3.0    2.0    3.0
4        4    2.0    2.0    2.0    2.0    2.0    2.0
5        5    3.0    3.0    3.0    3.0    2.0    2.0
6        6    3.0    3.0    3.0    3.0    2.0    3.0
7        7    1.0    1.0    1.0    1.0    1.0    1.0
8        8   12.5   12.5   14.1   15.2    5.2   12.5
9        9    9.2    9.2    9.4   10.4    3.4    8.5
10      10    2.0    2.0    2.0    2.0    1.0    2.0
11      11    1.0    1.0    1.0    1.0    1.0    1.0
12      12    1.0    1.0    1.0    1.0    1.0    1.0
13      13   12.5   12.5   13.6   15.2    5.1   13.2
14      14    1.0    1.0    1.0    1.0    1.0    1.0
15      15    1.0    1.0    1.0    1.0    1.0    1.0
16      16    1.0    1.0    1.0    1.0    1.0    1.0
17      17    1.0    1.0    1.0    1.0    1.0    1.0
18      18    1.0    1.0    1.0    1.0    1.0    1.0
19      19   12.0   12.0   13.0   14.5    8.8   11.8
20      20    1.0    1.0    1.0    1.0    1.0    1.0
21      21    1.0    1.0    1.0    1.0    1.0    1.0
22      22    1.0    1.0    1.0    1.0    1.0    1.0
23      23    7.6    7.6    8.3    8.6    3.0    5.0
24      24    7.5    7.5    7.5    8.6    2.0    3.0
25      25    6.9    6.9    6.9    8.4    2.4    5.0
26      26    1.0    1.0    1.0    1.0    1.0    1.0
27      27   10.3   10.3   10.6   11.8    3.5    9.0
28      28    9.9    9.9   10.5   11.0    4.7    8.4
29      29    2.0    2.0    2.0    2.0    2.0    2.0
30      30    8.7    8.7    9.3    9.7    2.0    7.0
31      31   13.0   13.0   15.0   16.7   10.8   13.5
32      32   12.0   12.0   14.0   16.3   12.3   14.0
33      33   12.0   12.0   16.6   17.2   14.0   15.4
34      lp  202.5  202.5  221.7  240.5  123.6  196.8

In [44]:
with open('../result/karate_lp.tex', 'w') as tf:
     tf.write(
          result[[
         'vertice',
          'bb',#'tk',
          'bb_a',#'tk_a',
          'bb_b',#'tk_b',
          'bb_c',#'tk_c',
          'bb_d',#'tk_d',
          'bb_e'#,'tk_e'
    ]].to_latex(index=False,float_format="%.1f")
)

/tmp/ipykernel_116742/1543939166.py:3: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  result[[