In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
inst_="karate"
method_="mip"
ver_="fmin"

In [4]:
form_="fminc1"

file=f"../result/{inst_}/{method_}/{ver_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminc1 = table
mip_karate_fminc1

#print(mip_karate_fminc1[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.05    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.15    8.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.06    5.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.17    9.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.08    5.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.09    7.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.14    8.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.23   13.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.21   12.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.16    4.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.11    7.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.20   10.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.02    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  1.70   94.0  34.0  21.0  0.23

In [5]:
form_="fminc2"

file=f"../result/{inst_}/{method_}/{ver_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminc2 = table
mip_karate_fminc2

#print(mip_karate_fminc2[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.01    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.11    5.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.06    3.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.11   10.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.05    7.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.07    7.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.12    7.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.12   14.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.12   11.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.07    5.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.08    7.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.10    9.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.02    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  1.07   91.0  34.0  21.0  0.12

In [6]:
form_="fminmiset"

file=f"../result/{inst_}/{method_}/{ver_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminmiset = table
mip_karate_fminmiset

#print(mip_karate_fminmiset[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   20.0   20.0  0.0  0.00    1.0   1.0   NaN   NaN
1        1   20.0   20.0  0.0  0.00    1.0   1.0   NaN   NaN
2        2   18.0   18.0  0.0  0.00    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   18.0   18.0  0.0  0.00    1.0   1.0   NaN   NaN
9        9   18.0   18.0  0.0  0.01    1.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   18.0   18.0  0.0  0.00    1.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   18.0   18.0  0.0  0.01    1.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   18.0   18.0  0.0  0.01    1.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.05    9.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.04    8.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   18.0   18.0  0.0  0.01    1.0   1.0   NaN   NaN
28      28   18.0   18.0  0.0  0.00    1.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   18.0   18.0  0.0  0.00    1.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.00    1.0   1.0   NaN   NaN
32      32   18.0   18.0  0.0  0.00    1.0   1.0   NaN   NaN
33      33   18.0   18.0  0.0  0.00    1.0   1.0   NaN   NaN
34     mip  322.0  322.0  0.0  0.13   31.0  34.0  20.0  0.05

In [7]:
form_="fminmisetc2"

file=f"../result/{inst_}/{method_}/{ver_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminmisetc2 = table
mip_karate_fminmisetc2

#print(mip_karate_fminmisetc2[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.01    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.14    3.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.12    8.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.06    1.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.09    5.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.14    7.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.22    7.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.30    3.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.12    3.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.09    5.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.13    4.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  1.47   53.0  34.0  21.0   0.3

In [8]:
form_="fminmisetc3"

file=f"../result/{inst_}/{method_}/{ver_}/{method_}_{form_}_{inst_}.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['vertice','bb','bs','gap','time','nodes','opt']

resume = pd.DataFrame({
    'vertice':f"{method_}",
    'bb':table["bb"].sum(),
    'bs':table["bs"].sum(),
    'gap':table['gap'].sum(),
    'time':table['time'].sum(),
    'nodes':table['nodes'].sum(),
    'opt':table['opt'].sum(),
    "tk":table["bs"].max(),
    "tmax":table["time"].max()
    },index=[f"{form_}"]
)

table = pd.concat([table, resume], ignore_index=True)
mip_karate_fminmisetc3 = table
mip_karate_fminmisetc3

#print(mip_karate_fminmisetc3[['vertice','bb','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

   vertice     bb     bs  gap  time  nodes   opt    tk  tmax
0        0   21.0   21.0  0.0  0.01    1.0   1.0   NaN   NaN
1        1   21.0   21.0  0.0  0.08    1.0   1.0   NaN   NaN
2        2   19.0   19.0  0.0  0.00    1.0   1.0   NaN   NaN
3        3    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
4        4    2.0    2.0  0.0  0.00    1.0   1.0   NaN   NaN
5        5    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
6        6    3.0    3.0  0.0  0.00    0.0   1.0   NaN   NaN
7        7    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
8        8   19.0   19.0  0.0  0.00    1.0   1.0   NaN   NaN
9        9   19.0   19.0  0.0  0.09    5.0   1.0   NaN   NaN
10      10    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
11      11    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
12      12    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
13      13   19.0   19.0  0.0  0.04    1.0   1.0   NaN   NaN
14      14    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
15      15    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
16      16    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
17      17    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
18      18    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
19      19   19.0   19.0  0.0  0.04    1.0   1.0   NaN   NaN
20      20    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
21      21    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
22      22    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
23      23   19.0   19.0  0.0  0.12    5.0   1.0   NaN   NaN
24      24   19.0   19.0  0.0  0.10    8.0   1.0   NaN   NaN
25      25   19.0   19.0  0.0  0.07    8.0   1.0   NaN   NaN
26      26    1.0    1.0  0.0  0.00    0.0   1.0   NaN   NaN
27      27   19.0   19.0  0.0  0.08    5.0   1.0   NaN   NaN
28      28   19.0   19.0  0.0  0.12    1.0   1.0   NaN   NaN
29      29    2.0    2.0  0.0  0.00    0.0   1.0   NaN   NaN
30      30   19.0   19.0  0.0  0.07    7.0   1.0   NaN   NaN
31      31   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
32      32   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
33      33   19.0   19.0  0.0  0.01    1.0   1.0   NaN   NaN
34     mip  335.0  335.0  0.0  0.85   49.0  34.0  21.0  0.12

In [9]:
fmin_mip_karate = pd.DataFrame()

fmin_mip_karate = pd.merge(
    mip_karate_fminc1, mip_karate_fminc2,
    on=['vertice'], 
    suffixes=("", "_b"),
    )

fmin_mip_karate = pd.merge(
    fmin_mip_karate, mip_karate_fminmiset,
    on=['vertice'], 
    suffixes=("", "_c"),
    )

fmin_mip_karate = pd.merge(
    fmin_mip_karate, mip_karate_fminmisetc2,
    on=['vertice'], 
    suffixes=("", "_d"),
    )

fmin_mip_karate = pd.merge(
    fmin_mip_karate, mip_karate_fminmisetc3,
    on=['vertice'], 
    suffixes=("", "_e"),
    )

In [11]:
fmin_mip_karate[[
    'vertice',
    'bs','gap','time','opt','tk','tmax',
    'bs_b','gap_b','time_b','opt_b','tk_b','tmax_b',
    'bs_c','gap_c','time_c','opt_c','tk_c','tmax_c',
    'bs_d','gap_d','time_d','opt_d','tk_d','tmax_d',
    'bs_e','gap_e','time_e','opt_e','tk_e','tmax_e'    
    ]]

,vertice,bs,gap,time,opt,tk,tmax,bs_b,gap_b,time_b,...,time_d,opt_d,tk_d,tmax_d,bs_e,gap_e,time_e,opt_e,tk_e,tmax_e
0,0,21.0,0.0,0.05,1.0,NaN,NaN,21.0,0.0,0.01,...,0.01,1.0,NaN,NaN,21.0,0.0,0.01,1.0,NaN,NaN
1,1,21.0,0.0,0.15,1.0,NaN,NaN,21.0,0.0,0.11,...,0.14,1.0,NaN,NaN,21.0,0.0,0.08,1.0,NaN,NaN
2,2,19.0,0.0,0.01,1.0,NaN,NaN,19.0,0.0,0.01,...,0.01,1.0,NaN,NaN,19.0,0.0,0.00,1.0,NaN,NaN
3,3,3.0,0.0,0.00,1.0,NaN,NaN,3.0,0.0,0.00,...,0.00,1.0,NaN,NaN,3.0,0.0,0.00,1.0,NaN,NaN
4,4,2.0,0.0,0.00,1.0,NaN,NaN,2.0,0.0,0.00,...,0.00,1.0,NaN,NaN,2.0,0.0,0.00,1.0,NaN,NaN
5,5,3.0,0.0,0.00,1.0,NaN,NaN,3.0,0.0,0.00,...,0.00,1.0,NaN,NaN,3.0,0.0,0.00,1.0,NaN,NaN
6,6,3.0,0.0,0.00,1.0,NaN,NaN,3.0,0.0,0.00,...,0.00,1.0,NaN,NaN,3.0,0.0,0.00,1.0,NaN,NaN
7,7,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
8,8,19.0,0.0,0.06,1.0,NaN,NaN,19.0,0.0,0.06,...,0.01,1.0,NaN,NaN,19.0,0.0,0.00,1.0,NaN,NaN
9,9,19.0,0.0,0.17,1.0,NaN,NaN,19.0,0.0,0.11,...,0.12,1.0,NaN,NaN,19.0,0.0,0.09,1.0,NaN,NaN
10,10,2.0,0.0,0.00,1.0,NaN,NaN,2.0,0.0,0.00,...,0.00,1.0,NaN,NaN,2.0,0.0,0.00,1.0,NaN,NaN
11,11,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
12,12,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
13,13,19.0,0.0,0.08,1.0,NaN,NaN,19.0,0.0,0.05,...,0.06,1.0,NaN,NaN,19.0,0.0,0.04,1.0,NaN,NaN
14,14,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
15,15,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
16,16,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
17,17,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
18,18,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
19,19,19.0,0.0,0.09,1.0,NaN,NaN,19.0,0.0,0.07,...,0.09,1.0,NaN,NaN,19.0,0.0,0.04,1.0,NaN,NaN
20,20,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
21,21,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
22,22,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
23,23,19.0,0.0,0.14,1.0,NaN,NaN,19.0,0.0,0.12,...,0.14,1.0,NaN,NaN,19.0,0.0,0.12,1.0,NaN,NaN
24,24,19.0,0.0,0.23,1.0,NaN,NaN,19.0,0.0,0.12,...,0.22,1.0,NaN,NaN,19.0,0.0,0.10,1.0,NaN,NaN
25,25,19.0,0.0,0.21,1.0,NaN,NaN,19.0,0.0,0.12,...,0.30,1.0,NaN,NaN,19.0,0.0,0.07,1.0,NaN,NaN
26,26,1.0,0.0,0.00,1.0,NaN,NaN,1.0,0.0,0.00,...,0.00,1.0,NaN,NaN,1.0,0.0,0.00,1.0,NaN,NaN
27,27,19.0,0.0,0.16,1.0,NaN,NaN,19.0,0.0,0.07,...,0.12,1.0,NaN,NaN,19.0,0.0,0.08,1.0,NaN,NaN
28,28,19.0,0.0,0.11,1.0,NaN,NaN,19.0,0.0,0.08,...,0.09,1.0,NaN,NaN,19.0,0.0,0.12,1.0,NaN,NaN
29,29,2.0,0.0,0.00,1.0,NaN,NaN,2.0,0.0,0.00,...,0.00,1.0,NaN,NaN,2.0,0.0,0.00,1.0,NaN,NaN
30,30,19.0,0.0,0.20,1.0,NaN,NaN,19.0,0.0,0.10,...,0.13,1.0,NaN,NaN,19.0,0.0,0.07,1.0,NaN,NaN
31,31,19.0,0.0,0.02,1.0,NaN,NaN,19.0,0.0,0.02,...,0.01,1.0,NaN,NaN,19.0,0.0,0.01,1.0,NaN,NaN
32,32,19.0,0.0,0.01,1.0,NaN,NaN,19.0,0.0,0.01,...,0.01,1.0,NaN,NaN,19.0,0.0,0.01,1.0,NaN,NaN
33,33,19.0,0.0,0.01,1.0,NaN,NaN,19.0,0.0,0.01,...,0.01,1.0,NaN,NaN,19.0,0.0,0.01,1.0,NaN,NaN
34,mip,335.0,0.0,1.70,34.0,21.0,0.23,335.0,0.0,1.07,...,1.47,34.0,21.0,0.3,335.0,0.0,0.85,34.0,21.0,0.12

In [12]:
print(
fmin_mip_karate[[
    'vertice',
    'bs','gap','time','opt','tk','tmax',
    'bs_b','gap_b','time_b','opt_b','tk_b','tmax_b',
    'bs_c','gap_c','time_c','opt_c','tk_c','tmax_c',
    'bs_d','gap_d','time_d','opt_d','tk_d','tmax_d',
    'bs_e','gap_e','time_e','opt_e','tk_e','tmax_e'    
    ]].to_latex(index=False,float_format="%.1f")
    )

\begin{tabular}{lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr}
\toprule
vertice &    bs &  gap &  time &  opt &   tk &  tmax &  bs\_b &  gap\_b &  time\_b &  opt\_b &  tk\_b &  tmax\_b &  bs\_c &  gap\_c &  time\_c &  opt\_c &  tk\_c &  tmax\_c &  bs\_d &  gap\_d &  time\_d &  opt\_d &  tk\_d &  tmax\_d &  bs\_e &  gap\_e &  time\_e &  opt\_e &  tk\_e &  tmax\_e \\
\midrule
      0 &  21.0 &  0.0 &   0.1 &  1.0 &  NaN &   NaN &  21.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  20.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  21.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  21.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      1 &  21.0 &  0.0 &   0.1 &  1.0 &  NaN &   NaN &  21.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  20.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  21.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  21.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
      2 &  19.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      3 &   3.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      4 &   2.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      5 &   3.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      6 &   3.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   3.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      7 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      8 &  19.0 &  0.0 &   0.1 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
      9 &  19.0 &  0.0 &   0.2 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
     10 &   2.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     11 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     12 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     13 &  19.0 &  0.0 &   0.1 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     14 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     15 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     16 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     17 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     18 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     19 &  19.0 &  0.0 &   0.1 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     20 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     21 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     22 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     23 &  19.0 &  0.0 &   0.1 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
     24 &  19.0 &  0.0 &   0.2 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.2 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
     25 &  19.0 &  0.0 &   0.2 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.3 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
     26 &   1.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   1.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     27 &  19.0 &  0.0 &   0.2 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
     28 &  19.0 &  0.0 &   0.1 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
     29 &   2.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &   2.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     30 &  19.0 &  0.0 &   0.2 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.1 &    1.0 &   NaN &     NaN \\
     31 &  19.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     32 &  19.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
     33 &  19.0 &  0.0 &   0.0 &  1.0 &  NaN &   NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  18.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN &  19.0 &    0.0 &     0.0 &    1.0 &   NaN &     NaN \\
    mip & 335.0 &  0.0 &   1.7 & 34.0 & 21.0 &   0.2 & 335.0 &    0.0 &     1.1 &   34.0 &  21.0 &     0.1 & 322.0 &    0.0 &     0.1 &   34.0 &  20.0 &     0.1 & 335.0 &    0.0 &     1.5 &   34.0 &  21.0 &     0.3 & 335.0 &    0.0 &     0.8 &   34.0 &  21.0 &     0.1 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_22523/430872418.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  fmin_mip_karate[[

In [13]:
with open('../result/karate_mip.tex', 'w') as tf:
     tf.write(
          fmin_mip_karate[[
          'vertice',
          'bs','time',#'opt',#'tk','tmax',
          'bs_b','time_b',#'opt_b',#'tk_b','tmax_b',
          'bs_c','time_c',#'opt_c',#'tk_c','tmax_c',
          'bs_d','time_d',#'opt_d',#'tk_d','tmax_d',
          'bs_e','time_e',#'opt_e',#'tk_e','tmax_e',
          ]].to_latex(index=False,float_format="%.1f")
    )

/tmp/ipykernel_22523/1935890985.py:3: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  fmin_mip_karate[[